### ISSUE TITLE
No simple file save dialog for Keystore (UTC/JSON) file

### ISSUE THREAD

**Issue by pyskell** [EthereumCommonwealth/etherwallet#103]
The button to download a keystore/JSON file from CEW no longer works. When I click it I get a new window open to here: `blob:https://ethereumproject.github.io/f243f51d-c8ca-44f4-8e94-16bc644bb20e`

UUID will change each time I create a new wallet.

![image](https://user-images.githubusercontent.com/9665963/38204246-2c032a48-3670-11e8-8fad-2c3c52ff6cf2.png)

**Comment by Dexaran** [comment]
Confirmed.
This needs to be fixed ASAP @j-chimienti
