### ISSUE TITLE
uBlock Origin prevents downloading of Keystore file (UTC/JSON)

### ISSUE THREAD

**Issue by pyskell** [EthereumCommonwealth/etherwallet#104]
Seems to be related to the pop-up blocking functionality of uBlock Origin.

Also likely related to #103

**Comment by j-chimienti** [comment]
I think issue is resolved. I installed uBlock origin chrome extension and can download file.

issue #103 was closed and file is downloading

**Comment by pyskell** [comment]
Confirmed, works for me as well!
