### ISSUE TITLE
Duplicate popup notification about node connection when loading/reloading CEW page.

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/etherwallet#108]
![dup](https://user-images.githubusercontent.com/26142412/38290740-a682937a-37d4-11e8-9169-2a0f5fdc44e2.png)

**Comment by j-chimienti** [comment]
I believe this is happening due to the tabsCtrl being initialized twice.

Could be due to faulty html,  second injecting of controller.
