### ISSUE TITLE
CEW mobile version does not work anymore.

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/etherwallet#109]
### Description

CEW does not display proper buttons and tabs after I load it on my smartphone. It shows some variable names and broken drop-down lists, as if the markdown was broken.

![screenshot_2018-04-04-14-39-39](https://user-images.githubusercontent.com/26142412/38304331-e9c35cb0-3800-11e8-8852-ae3dc05c2c21.png)

**Comment by j-chimienti** [comment]
Confirmed:

Safari:

![cew_mobile_safari](https://user-images.githubusercontent.com/16620120/38309130-278445e2-37e7-11e8-9bdd-d185e35f9caa.png)

Chrome:


![cew_mobile_chrome](https://user-images.githubusercontent.com/16620120/38309133-2935cbe0-37e7-11e8-8366-196b83055d88.png)
