### ISSUE TITLE
Unable to send ETC w/ Ledger wallet

### ISSUE THREAD

**Issue by j-chimienti** [EthereumCommonwealth/etherwallet#116]
**Issue:**

Cannot send ETC w/ Ledger wallet

**Quote:**
> Hello im unable to send ETC via https://ethereumproject.github.io/etherwallet using ledger. Account you are sending from does not have enough funds. If sending tokens, you must have 0.01 ETC in your account to cover the cost of gas. Even i have plenty ETC.

cReepas, via discord.

**Comment by Dexaran** [comment]
https://www.reddit.com/r/CallistoCrypto/comments/8ctmjy/sending_clo_via_cew_ledger_nano_s/ yeah, it seems that the problem appears after the last PRs.

**Comment by Haxiboy** [comment]
I get this message on all coins with ledger wallet, and connecting to ledger and generating TX also opens Trezor's Webpage
