### ISSUE TITLE
Error: Send Callisto (CLO) on Classic Ether Wallet (CEW)

### ISSUE THREAD

**Issue by redcloud1900** [EthereumCommonwealth/etherwallet#117]
hi everyone,
i was so far unable to **send** **callisto** using **CEW**.
what i did:
- open _classicetherwallet.com_
- '_send ether and tokens_'
- access via trezor, export public key -> open my ETC wallet, which holds ETC and Callisto
- switch network from 'ETC - epoo.io' to '**CLO** - callisto.network'
- filling in receiving adress, amount to send, ...
- generate transaction with trezor => trezor doesn't know **CLO**, it says 'send ### UNKN' but it still generates the transaction
- broadcasting transaction => popup warning says 'You are about to send ### **CLO** - You are interacting with the **CLO** chain, provided by Callisto.network.' => ok, send => Error Message: ...your account does not have enough funds... must have **0.01 CLO** .... to cover cost of gas. of course i do have more than **0.01 CLO**, it also shows the balance of **ETC & CLO** initially on the right-hand side

can you tell me a solution for this problem? any other way to send those **CLO**?

thank you

**Comment by j-chimienti** [comment]
Thanks for the detailed writeup.

UNKN chain? strange, I don't think that's a coin, and a quick search came up w/ nothing. 

**Overall:**

1. You can connect to trezor and view balances.

1. Issue w/ generate tx (chain error).

1. Issue w/ sending tx  (insufficient balance error).

**Comment by apuzankov** [comment]
same error whith Trezor!!!

**Comment by apuzankov** [comment]
and, what a problem???!!!

**Comment by j-chimienti** [comment]
yes, frustrating. Especially since other methods work correctly.

I will have a patch soon.

**Comment by apuzankov** [comment]
ok

**Comment by lastbattle** [comment]
Hi. It is tested on the Ledger S too.

"Account you are sending from does not have enough funds. If sending tokens, you must have 0.01 CLO in your account to cover the cost of gas."

Thanks for your help!

**Comment by tatam3x** [comment]
i have the same issue with ledger nano !!! very disapointed

**Comment by j-chimienti** [comment]
issue relies w/ chainId.

https://github.com/trezor/connect#sign-ethereum-transaction

chainId field is optional, but useful for display purposes (eth = 1, etc = 61, ubq = 8). passing in chainId = 820 (CLO) results in errors.

Setting field to null for CLO, I can move from device, but coin is unknown and displays UNKN.

I have PR to fix tx error w/ trezor.

We could reach out to wallet companies for support of CLO chain, or CEW in general

**Comment by Haxiboy** [comment]
Same problem with Ledger Wallet

**Comment by redcloud1900** [comment]
I can confirm that it works now with trezor. The "UNKN" unknown chain-problem doesn't bother me personally....

Thanks for fixing!

**Comment by lastbattle** [comment]
Hi, I've just tested it once again after the #118 pull request.

The problem with this fix is that it causes the Trezor window to be opened even if it is connected via Ledger. Moreover the issue of "must have 0.01 CLO .... to cover cost of gas" still persist. 

<img width="461" alt="trezor" src="https://user-images.githubusercontent.com/4586194/39311074-8ae251f6-499e-11e8-9e71-ab9175aad415.PNG">

<img width="616" alt="capture" src="https://user-images.githubusercontent.com/4586194/39311079-8cbe26ee-499e-11e8-9dff-07cf074a0f22.PNG">

**Comment by j-chimienti** [comment]
I've fixed the popup w/ https://github.com/EthereumCommonwealth/etherwallet/commit/6baaff3ac2692a4712cfc1cb77fe6d24451d7494 , the app needs to be built for changes to be included


also, https://github.com/EthereumCommonwealth/etherwallet/pull/123 should give better insight to error

**Comment by tatam3x** [comment]
Eaxvac  had exaclty the same issue than me..

**Comment by cypheron** [comment]
@Dexaran Why did you remove "high_priority"? Makes no sense. A lot of community members are not able to access any of their funds at all. Please, have a thorough look (incl. heavy testing) on this and related hardware wallet issues and provide a timely fix.

**Comment by cypheron** [comment]
#136 works for me.
