### ISSUE TITLE
Message system update: popup notifications.

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/etherwallet#120]
### Description

It is necessary to add a popup notification that will shot up when the messages are loaded. (Send Ether & Tokens tab after a user unlocked his account)

Notification should represent the following texts:

- You have `<number>` recent messages!

- `View messages` button that will redirect a user to the "Messages" tab preserving his private key (keeping the account unlocked).

**Comment by j-chimienti** [comment]
will popup open only open on inital page load, if 0 < recent messages? 

or

will it also listen for new messages and notify user

**Comment by Dexaran** [comment]
Only on initial page load.

There is no need to listen for incoming messages. It is not an online chat but an emergency way to contact an owner of an address.

**Comment by Dexaran** [comment]
Done.
