### ISSUE TITLE
Did Not Receive Callisto from ETC fork

### ISSUE THREAD

**Issue by RoseM2018** [EthereumCommonwealth/etherwallet#127]
Hi there,  I did not receive Callisto from the ETC fork in March.   ON ETC (https://gastracker.io) I see the transactions into the wallet and out of the wallet:  showed 1004 transferred out, block 5500380.  The fork/snapshot occurred at block 5500000.
Tokens (Ethplorer.io) showed no Callisto or any tokens.   There were no transfer of tokens out or in so I don't believe I was hacked.   Help, what can I do clearly something is wrong?

**Comment by yograterol** [comment]
@RoseM2018 what is your address?

Callisto is not an ERC20 token.
