### ISSUE TITLE
Unable to send Pirl with Ledger Wallet

### ISSUE THREAD

**Issue by Haxiboy** [EthereumCommonwealth/etherwallet#137]
I'm getting error "Invalid sender" when trying to confirm a transaction on pirl blockchain with Ledger Nano S

**Comment by j-chimienti** [comment]
Most likely an issue signing tx w/ EIP-155 support. We had similar issues w/ CLO.

[issues] (https://forum.pirl.io/t/storing-pirl-using-mew-via-trezor/140/9) has been known and issues are still present in other sites as well.

The hardware devices reject signing tx for the networks, and had to remove EIP-155 support for CLO, we can do the same for Pirl

**Comment by Haxiboy** [comment]
Dont close it unless it's solved.

**Comment by mkrufky** [comment]
@Haxiboy I have a *temporary* version of a forked etherwallet that you can use to recover your PIRL at https://mkrufky.github.io/etherwallet   ...  I can't promise it will stay there for very long, but hopefully an official fix will get merged sooner or later.

**Comment by mkrufky** [comment]
btw, thanks to @j-chimienti ... my fix was i̶n̶s̶p̶i̶r̶e̶d̶ ̶b̶y̶ copied from his CLO fix
