### ISSUE TITLE
CEW breaks oddly in Chrome, only when regularly browsing

### ISSUE THREAD

**Issue by pyskell** [EthereumCommonwealth/etherwallet#147]
Incognito mode works, Firefox works, Chrome on other machines work.

Attempted fixes: Clearing cookies, cache. Did not work.

Chrome version: 66.0.3359.181 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/9665963/40493161-21bfe0be-5f40-11e8-82a8-8f859dca7a0b.png)
![image](https://user-images.githubusercontent.com/9665963/40493179-28fa10c0-5f40-11e8-991f-e0d8d16f47c6.png)

**Comment by j-chimienti** [comment]
looks like an error saving / loading the custom node locally.

can u provide output to:

```
localStorage.localNodes
> "[{"options":"etc","name":"testing etc","url":"http://localhost","port":"8545","httpBasicAuth":null,"eip155":true,"chainId":"61"}]"

```

**Comment by pyskell** [comment]
```
localStorage.localNodes
"[{"options":"etc","name":"localhost","url":"http://127.0.0.1","port":"8545","httpBasicAuth":null,"eip155":false,"chainId":""}]"
```

**Comment by j-chimienti** [comment]
I can confirm issue when not setting chainId and eip settings when saving local node.

I should edit component to default to network setting unless overridden by user

**Comment by pyskell** [comment]
Did this make it to the live site? It's still broken for me.
