### ISSUE TITLE
dexns name display / end time / remaining time

### ISSUE THREAD

**Issue by j-chimienti** [EthereumCommonwealth/etherwallet#191]
I am calling assignation from storage contract to return name assigned to addr

Issues:

name: dexaran not assigned to an addr

When registering name, name is not assigned.

And in registerAndUpdateName it is optional

### User Info
<img width="1109" alt="screen shot 2018-07-12 at 11 36 14 am" src="https://user-images.githubusercontent.com/16620120/42652649-ef498a50-85c7-11e8-8b28-dfb4f43b8497.png">

<img width="1064" alt="screen shot 2018-07-12 at 11 58 22 am" src="https://user-images.githubusercontent.com/16620120/42653668-f0140976-85ca-11e8-9c43-7460553bb0be.png">

### Dexns Display

<img width="342" alt="screen shot 2018-07-12 at 11 36 29 am" src="https://user-images.githubusercontent.com/16620120/42652648-ef2a9fa0-85c7-11e8-9702-524542362a76.png">

**Comment by Dexaran** [comment]
There are no problems here.

If the address does not have an "assigned" name, it is the same as "the address does not have a name yet".

(Address can own multiple names, thus autoassigning a name after the registration is optional)
