### ISSUE TITLE
DexNS token registration update.

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/etherwallet#216]
1. DexNS must check whether a name is available for registration OR already registered.

2. It is necessary to provide a possibility to register token contract address (this should be [_destination](https://github.com/EthereumCommonwealth/DexNS/blob/master/DexNS_Storage.sol#L103) property of the Name). NOTE: This is not an optional parameter unlike link, source code and info description.

**Comment by j-chimienti** [comment]
I will reopen PR #223 once issue #217 is resolved
