### ISSUE TITLE
BUG: name management (name assignation)

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/etherwallet#218]
Name `i3` is assigned to 0x01000B5fE61411C466b70631d7fF070187179Bbf address.

![cew_bug3](https://user-images.githubusercontent.com/26142412/43710175-cfe83e7e-9966-11e8-844e-ce19443b6fcf.png)

**Comment by j-chimienti** [comment]
**branch**:

https://github.com/j-chimienti/etherwallet/tree/fix/contract-call-%23218

I am in final testing phase, and expect PR this week

**Issue** not handling case of multiple functions with same name in contract.

find abi by name, which locates first one (bytes input) and resolves incorrectly

**changes:**

I've started to make the Contract class accept sending / calling tx via name or function

this is a big change, and am going through the app making sure I haven't broken anything.



### Send Tx

* [x] ledger https://rinkeby.etherscan.io/tx/0x259c1f96f86318f8d6de0a8591aaee57328cf3df185a2f67e91c95c5a8d6e697
* [x] trezor https://rinkeby.etherscan.io/tx/0x30463d62cdad9794e50f5e6a585beb733854c6cad05ab1c9525af9402b040185
* [x] web3 https://rinkeby.etherscan.io/tx/0xf68c72c7dfbf9b1538554b9074957609c3fdf09da16bfa76a2bb30808fa41467
* [x] private key https://rinkeby.etherscan.io/tx/0x07b31854480e50cc86a551b61ada322f0fafb4265bd27674bbeceb30b477562b




### Cold Staking

* [x] ledger https://rinkeby.etherscan.io/tx/0x5296dffc8ccb3480fd78b2675295cb4abbbf4b0cfc32802504a2f8c6177cb66e

successful txs in send tx page and contracts page


### Contracts

##### Deploy

* [x] Contract w/ contructor params (array) Multisig wallet https://rinkeby.etherscan.io/tx/0xc9bddc3f59e93e5ad1ae8292fb01fa20e2326a43802f438a65e2456d438d2540

* [x] -> ledger https://rinkeby.etherscan.io/tx/0x3140aae85ae48b3348f98ba44f8dd7bf1cccb2cc0e4055aee797fcd7d35ba71a deploy saving wallet

* [x] -> trezor https://rinkeby.etherscan.io/tx/0x53ccd6e7d26dc108d108078d96172f65ccdec1badb8abac7fa2db9191189d61d

##### Interact

* [x] -> ledger cold staking -> rinkeby eth -> first stake donation https://rinkeby.etherscan.io/tx/0x5296dffc8ccb3480fd78b2675295cb4abbbf4b0cfc32802504a2f8c6177cb66e


* [x] -> ledger cold staking -> rinkeby eth -> dnate
https://rinkeby.etherscan.io/tx/0xce1d0369d728d205f1a8e297346c3f8ee007b82ba0533911972ca293508949fb

### Dexns

* [x] calling function (name_assignation) 
* [x] executing function
* [x] register name (testnet) -> trezor https://rinkeby.etherscan.io/tx/0x57f5163892af9f7add1852d1e940404984dc9761c15f5fc079dc8ee618089f03
* [x] extend name (testnet) -> trezor -> https://rinkeby.etherscan.io/tx/0x49bc92ab42616bc58196103d4ab45cf58a7cdfad36606fe98336b36ddd38f3c8
* [x] append metadata (testnet) -> trezor -> https://rinkeby.etherscan.io/tx/0x35908d163cbc3a5b9835163dbf9d2706c53edcbcd9d5547b161d0541ba423efd

* [x] updateName -> trezor fix metadata https://rinkeby.etherscan.io/tx/0xceb35db36f3bcaebe4c1cbda51dcade029a82f79d7ad293fcf43bb39e4c104ef
