### ISSUE TITLE
Trezor One Wallet doesn't generate transaction in CLO chain

### ISSUE THREAD

**Issue by yograterol** [EthereumCommonwealth/etherwallet#267]
Trezor One Wallet doesn't generate transaction, click on the button and nothing happen.

![image](https://user-images.githubusercontent.com/3322886/45897099-c7889e00-bd9b-11e8-90ef-13dbc307f53b.png)

No error on console tab.

cc @j-chimienti

**Comment by yograterol** [comment]
Randomly it works however show this error

![image](https://user-images.githubusercontent.com/3322886/45897275-4bdb2100-bd9c-11e8-90f6-aa98d7aef3f1.png)

**Comment by j-chimienti** [comment]
There is an issue sending tx over CLO & Testnet CLO  networks w/ trezor w/ older firmware

Network         | Send Tx
------------- | :--------------------------: 
Testnet CLO  | <ul><li> 👎 Trezor (insufficient balance err) </li><li> 👍 Priv Key [startStaking() tx](https://explorer-testnet.callisto.network/tx/0x755c03b5a162307142b7196dd3d8e6e96e27fc7dafe1686b4540d2f6ebf6cf83)</li></ul>
CLO                | <ul><li> 👎 Trezor (insufficient balance err) </li><li> 👍 Priv Key</li></ul>
RINKEBY        | <ul><li> 👍 Trezor [startStaking() tx](https://rinkeby.etherscan.io/tx/0xe4b2cfbf0964a2603082288ee1f8696b93343433f9f6c58378ca659776aa812b) </li><li> 👍 Priv Key</li></ul>

**Comment by j-chimienti** [comment]
**Update Trezor to firmware 1.6.3** and txs will work over CLO

Network | Send Tx (Trezor)
--- | ---
CLO | 👍 [tx](https://explorer2.callisto.network/tx/0x60948d1f104aaf7d59706a2d6ef41735ef7a1100af4069746e54765428d56aba)
Testnet CLO |  👍 [tx](https://explorer-testnet.callisto.network/tx/0xefdf89930ee1b1bad125fb7302ad6e2c04a853305fd7ab878c8695ef2f2aac07) <br/> 👍 [startStaking tx](https://explorer-testnet.callisto.network/tx/0x41facfbbf4cded2b6f67433589f4784d243a0f89245ef5330e1461d8bcdc61cc)


**User needs to be notified if firmware under 1.6.3**

**Comment by j-chimienti** [comment]
Trezor Connect has also upgraded to v5 see #273

**Comment by yograterol** [comment]
Trezor tested by myself and I got the same result of @j-chimienti
