### ISSUE TITLE
staker() time 

### ISSUE THREAD

**Issue by j-chimienti** [EthereumCommonwealth/etherwallet#296]
<img width="1189" alt="screen shot 2018-11-07 at 4 10 26 pm" src="https://user-images.githubusercontent.com/16620120/48161081-b80bd880-e2a7-11e8-9820-09732fe24528.png">

seems staker().time returning current time, not staking time

**Comment by Dexaran** [comment]
`staker.time` returns the timestamp of the last action of a given staker address.

It seems that everything is fine with my address 0x01000b5fe61411c466b70631d7ff070187179bbf

The timestamp `1540732910` is 10/28/2018

Last TX timestamp is also 10/28/2018:
https://explorer-testnet.callisto.network/tx/0xb4f49807155490ce54bda08e9490b362e16d178f16dbad913ea79c4e796836e9

![epochconverter](https://user-images.githubusercontent.com/26142412/48186858-b519f200-e352-11e8-8299-a068a1d5b2d7.png)

**Comment by Dexaran** [comment]
We need to subtract the returned amount from `now.timestamp` to know how long a staker is staking.

**Comment by j-chimienti** [comment]
#### Address 0x01000b5fe61411c466b70631d7ff070187179bbf 

is showing correct info



<img width="372" alt="screen shot 2018-11-08 at 6 42 38 am" src="https://user-images.githubusercontent.com/16620120/48196775-8172a400-e321-11e8-86bc-cd05bb480af3.png">


<img width="1175" alt="screen shot 2018-11-08 at 6 52 37 am" src="https://user-images.githubusercontent.com/16620120/48197167-eaa6e700-e322-11e8-8932-2ef722686636.png">


#### Addr 0x024d8a6a6613ed0bd35b80ab9096e07fbf898443

Explorer missing txs and showing last timestamp at 2018-11-02 08:12

https://explorer-testnet.callisto.network/addr/0x024d8a6a6613ed0bd35b80ab9096e07fbf898443


<img width="357" alt="screen shot 2018-11-08 at 6 43 07 am" src="https://user-images.githubusercontent.com/16620120/48196795-951e0a80-e321-11e8-96eb-35cd6878f45a.png">




<img width="1147" alt="screen shot 2018-11-08 at 6 46 17 am" src="https://user-images.githubusercontent.com/16620120/48196963-1bd2e780-e322-11e8-9ee1-e6d9c3385422.png">


Staker Time: '2018-11-8 06:44:56'

I haven't made any txs on this date

**Comment by Dexaran** [comment]
The issue is resolved.
