### ISSUE TITLE
Can't send 1000 or more CLO to CS and low Gas amount.

### ISSUE THREAD

**Issue by yuriy77k** [EthereumCommonwealth/etherwallet#297]
When I try to send 1000 or more CLO to Cold Staking contract via UI, I get this error:
![2018-11-04_205943](https://user-images.githubusercontent.com/39490997/48211422-1c02cf80-e382-11e8-96fe-08fad16a038b.jpg)
Sending less amount (999.99999 or less) may work, but transaction reverted. There is a problem with Gas calculation. Will be good to fix Gas amount to 150,000.

**Comment by Dexaran** [comment]
Resolved long time ago.
