### ISSUE TITLE
estimate gas evaluating when interacting w/ contract

### ISSUE THREAD

**Issue by j-chimienti** [EthereumCommonwealth/etherwallet#51]
![screen shot 2018-03-02 at 9 17 10 am](https://user-images.githubusercontent.com/16620120/36903169-e8f2a450-1dfa-11e8-8a11-1af059ac39a3.png)

Gas limit will need to be evaluated after clicking "write"

**Comment by Dexaran** [comment]
I suppose that it should be something like https://github.com/EthereumCommonwealth/etherwallet/issues/31 

There need to be a button for autoevaluation. When the button is clicked, an evaluation is performed.

Otherwise, rely on manually inputted value of the `Gas Limit` text field.
