### ISSUE TITLE
Change "Swap" exchange from BitY to ChangeNow

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/etherwallet#54]
https://changenow.io/

https://ethereumproject.github.io/etherwallet/#swap

**Comment by j-chimienti** [comment]
unlike bity, changenow has access-control-allow-origin policy.

We will have relay to a custom node

```


// No 'Access-Control-Allow-Origin' header is present on the requested resource. 
// Origin 'http://localhost:5000' is therefore not allowed access.

function getChangeNow() {
	
	var data = null;

	var xhr = new XMLHttpRequest();


	xhr.addEventListener("readystatechange", function () {
	  if (this.readyState === 4) {
	    console.log(this.responseText);
	  }
	});


	xhr.open("GET", "https://changenow.io/api/v1/currencies");
	xhr.send(data);



}


function getBity() {
	
	var data = null;

	var xhr = new XMLHttpRequest();

	xhr.addEventListener("readystatechange", function () {
	  if (this.readyState === 4) {
	    console.log(this.responseText);
	  }
	});

	xhr.open("GET", "https://bity.com/api/v1/rate2/");

	xhr.send(data);
}

```

**Comment by Dexaran** [comment]
So be it.

**Comment by ChangeNOW-Exchange** [comment]
Hi! 

Do you need any help with integration?
Please don’t hesitate to mention me here to get some help from ChangeNOW. We can also connect you directly to our developers, if necessary.

Let us know!

**Comment by j-chimienti** [comment]
Thanks for reaching out!

I've started to research the integration process, and seems that it will differ than our current implementation w/ bity.

I'm looking to dig in shortly, and certainly would appreciate help to questions that will arise.

✌

**Comment by ChangeNOW-Exchange** [comment]
Hey guys!

How is the process of ChangeNOW integration going? Is there anything we can help with? Let us know!

**Comment by j-chimienti** [comment]
I started to replace bity w/ changeNow

 [api wrapper](https://change-now.herokuapp.com/) 

**can:**
1. get list of coins /swap/currencies
1.  get get conversion rates b/w coins based off user input swap/exchange-amount/:amount/:from/:to

**todo:**
1. verify min amount.
1. process order

![screen shot 2018-05-09 at 12 35 05 pm](https://user-images.githubusercontent.com/16620120/39827288-88466392-5385-11e8-8649-c5b7d34f9725.png)

**Comment by ChangeNOW-Exchange** [comment]
Excellent, we are always ready to help you, we are waiting with impatience.

**Comment by j-chimienti** [comment]
Cool, I threw together a wrapper for the API, but would like input, as free deployment on heroku w/ nodejs isn't production grade. I'm thinking about PHP library you guys provide, but I don't have too much experience w/ PHP.  I could slog through w/ some help.

**Comment by ChangeNOW-Exchange** [comment]
We can offer Python library, which can also be used: https://github.com/ChangeNow-io/ChangeNOW-api-python

**Comment by j-chimienti** [comment]
Thanks, I didnt see the python library.

I've opened a PR and welcome comments / suggestions

**Comment by Dexaran** [comment]
@j-chimienti It is badly needed to implement a search option for swap currencies.
It is a real pain to search for my beloved EXP in a great list of different tokens without search.

**Comment by j-chimienti** [comment]
great minds think alike. I was working on typeahead this morn, I see u just merged.

I'm going to update stage-1 swap converstion ratio estimate and speed up. I can use conversion ratio from FE to limit BE calls

**Comment by ChangeNOW-Exchange** [comment]
Hi guys,

As I see, you added ChangeNOW to Swap.

I found a couple of errors:
1. I tried to exchange and the Swap button after input of the receiving address does not work.
2. When attempting to create exchange ETC to BTC, a reverse request for BTC to ETC was sent.

We would also like to suggest that using a convenient library to get SVG coin icons: https://github.com/guardaco/crypto-icons

Are there any issues we can help you with regarding this?

**Comment by j-chimienti** [comment]
Thanks for the notification of errors, I took a look at and seems ok now (open for suggestions).

I'm getting much faster response times estimating exchange rate by saving in FE.

Also thx for icons, I implemented and reduced the 40 some errors loading images. Guarda was fast to add CLO icon

If you find any more issues, please advise.

And maybe we'll see CLO integration soon, as it's making it's way onto more exchanges and listings.
