### ISSUE TITLE
Message system displays incorrect number of messages.

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/etherwallet#61]
### Description

0x01000B5fE61411C466b70631d7fF070187179Bbf address has 2 incoming messages while it has only 1 incoming message in fact.
(It is duplicate `Hello` message in this case)

![gazz1](https://user-images.githubusercontent.com/26142412/37308896-39bad58a-2637-11e8-8fff-61adb0dd00ba.png)

Messaging contract displays an empty default message at `0` index and `Hello` message at `1` index.

**Comment by Dexaran** [comment]
![gazz3](https://user-images.githubusercontent.com/26142412/37309386-b759ef8e-2638-11e8-8958-f9d59fb68e5e.png)
![gazz2](https://user-images.githubusercontent.com/26142412/37309387-b7fd6bd2-2638-11e8-846b-e032d1ef2949.png)

**Comment by Dexaran** [comment]
Then I've sent another message to the 0x01000B5fE61411C466b70631d7fF070187179Bbf address.
Now the MEssage System displays a correct number of messages and 2 messages without duplications.

![gazz4](https://user-images.githubusercontent.com/26142412/37309453-e355eff2-2638-11e8-9c85-a8b47e6aef69.png)

**Comment by j-chimienti** [comment]
Is this still outstanding, I'm unable to create issue on ETC network w/ view wallet address?
