### ISSUE TITLE
Incorrect message order. The last message overwrites previous one.

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/etherwallet#62]
### Description

I've sent `Message number 3` message ([transaction](https://gastracker.io/tx/0x320d30ef8fd1df35352c63147dbab0eaea654a0e288d47790b5ea65aed5d6ff9)) to `0x01000B5fE61411C466b70631d7fF070187179Bbf` address.

Now the Message System shows the following messages:

- Hello
- Message number 3 < < this is the bug
- Message number 3

`Message number 2` is not displayed properly.

![gazz5](https://user-images.githubusercontent.com/26142412/37309742-bd6ebb74-2639-11e8-81b1-62572e084abc.png)

**Comment by Dexaran** [comment]
@j-chimienti the issue still stands.

**Comment by j-chimienti** [comment]
k thx, can u upload results of `localStorage.getItem('@messages@')` I'm wondering if there was issue b/w fetching messages and saving. 

I think  easiest way to solve issue would be to save index with message, and adding check to see if we have missing / duplicate messages.
