### ISSUE TITLE
Messages tab lacks `View with Address Only` wallet access method

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/etherwallet#63]
### Description

There is an implementation of wallet access by address in [View Wallet Info tab](https://ethereumproject.github.io/etherwallet/#view-wallet-info).

The described functionality should also be applied to messages, because there is no need to decrypt your wallet for viewing messages.

![gazz6](https://user-images.githubusercontent.com/26142412/37310227-2a9bf030-263b-11e8-98f2-3c5c76b33ed1.png)

**Comment by j-chimienti** [comment]
I'll remove the new message component from view if view only.

And I'll add the toggle to switch wallet
