### ISSUE TITLE
Error: insufficient gas displays hardcoded `ETH` currency denominations

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/etherwallet#65]
### Description

It seems that currency denomination is hardcoded at error message. It must display the currency denomination in accordance with the chosen network.

![gazz7](https://user-images.githubusercontent.com/26142412/37310640-7bf59c00-263c-11e8-80c2-da3284036500.png)

**Comment by j-chimienti** [comment]
This issue should be closed.
