### ISSUE TITLE
gasPrice default mechanic change

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/etherwallet#71]
### Description

I received several complaints about the fact that the commissions in CEW are too large. Some users experiences issues with default values of gasPrice resetting to `53292765 Mwei`.

### TODO

- do not store/load gasPrice preferences anymore!

- reset gasPrice to 21GWei (default) **each time a user is approaching ClassicEtherWallet or changing network**.

- reset gasPrice to 2000GWei at Callisto testnet

**Comment by j-chimienti** [comment]
ok I'll remove the local storage saving, I updated so gasPrice !== NaN

**Comment by Dexaran** [comment]
@j-chimienti the problem still stands.
If you switch to CLO testnet then switch back to ETC network then the gasPrice will not autoreset to 21GWei.

Well... it is better to get rid of CLO high gas prices at all.

- it is necessary to reset gasPrice to 21GWei on each CEW loading OR on network switch.

- change the gasPrice range from `0.1 - 60 GWei` to `0.1 - 100 GWei`

- ~~if switching to CLO-testnet network then the gasPrice must be set to 2000GWei~~ get rid of CLO gasPrices at all

**Comment by Dexaran** [comment]
gasPrice ranging 0.1 - 100 GWei is fixed at https://github.com/EthereumCommonwealth/etherwallet/commit/65178b0e5cb5268a5a7804128b4636406984c049

CLO gasPrices list is also properly configured now.

**Comment by j-chimienti** [comment]
ok cool, I started to remove the localStorage functionality, but that was messing up gasPrice value in transaction.

**Comment by j-chimienti** [comment]
>>  get rid of CLO gasPrices at all

kk

**Comment by Dexaran** [comment]
@j-chimienti 


You'd better add an extra check for `gasPrice` validity at Generate Transaction step. `gasPrice` **must** be less than [max gas price](https://github.com/EthereumCommonwealth/etherwallet/blob/mercury/app/scripts/controllers/tabsCtrl.js#L72), greater than [min gas price](https://github.com/EthereumCommonwealth/etherwallet/blob/mercury/app/scripts/controllers/tabsCtrl.js#L73) and **valid** (not null, not undefined, not a letter or special character).

**Comment by Dexaran** [comment]
well...
`gasPrice` is currently defaulted to 20GWei regardless of what is set at the `gasPrice` input field.
This is necessary to implement a proper gasPrice configuration so that gasPrice changes apply.

**Comment by j-chimienti** [comment]
When generating transactions I see

network | gasPrice
---- | ---
ETC | ethFuncs.hexToDecimal('0x04a817c800')"20000000000"
CLO | ethFuncs.hexToDecimal('0x01d1a94a2000')"2000000000000"
ETH | ethFuncs.hexToDecimal('0x012a05f200') "5000000000"



and I don't think the manual gasPrice is overriding values either.

**Comment by Dexaran** [comment]
The gasPrice input field is configured now. It does not allow `NaN` or incorrect inputs anymore. It is necessary to make transaction gasPrice match the inputted gasPrice value.

**Comment by j-chimienti** [comment]
kk, and min and max is 0.1 and 100 respectively?  It's set initially at 10000 and 0 , line 83
