### ISSUE TITLE
Node is automatically switched to ETC (Epool) after wallet decryption.

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/etherwallet#81]
### Steps to reproduce

1. Switch the node to Kovan testnet (or any other node).

2. Unlock wallet.

3. The node will automatically switch to ETC Epool.  < - - this is a bug.

**Comment by Dexaran** [comment]
Also, this causes incorrect balance display order. For example if I unlock my wallet with MEW ETH network then it will show my ETC balance as 0 even if it is not equal to 0 really.

**Comment by j-chimienti** [comment]
```
 if (ajaxReq.type.toUpperCase() !== 'ETC') {

        $rootScope.$broadcast('ChangeNode', 'etc_epool');
    }


```

kk, I'll remove force change node. It was there initially to load messages over ajax, but we are now using etc node to make requests, and we now require network is ETC before sending messages.

`let node = nodes.nodeList.etc_epool;`

 Are we okay with epool, we can switch to commonwealth geth, i see we did the same for classic mask.

**Comment by j-chimienti** [comment]
>> incorrect balance display order

Noted, and I've seen this happen before, not today though. For most calls, the balance comes back correctly, but sometimes request fails. I think when this happens, the balance is set to 0. But it should display / notify err.


![screen shot 2018-03-20 at 8 43 53 am](https://user-images.githubusercontent.com/16620120/37655158-e13e3eee-2c1a-11e8-80bc-660bdd660842.png)
