### ISSUE TITLE
Can't send message after unlocking wallet

### ISSUE THREAD

**Issue by pyskell** [EthereumCommonwealth/etherwallet#86]
When I unlock my wallet I can only list messages. I can only see the send message function when I don't have a wallet unlocked.

This is using a Trezor wallet. When using ClassicMask I am able to see both options.

![image](https://user-images.githubusercontent.com/9665963/37781357-ed07bfae-2dc6-11e8-9b44-5957fb9a3024.png)

**Comment by Dexaran** [comment]
This may be caused by the fact that you are working through Trezor.
There were no problems detected with Keystore files btw.

**Comment by pyskell** [comment]
Yeah, agreed, Trezor strikes again

**Comment by Dexaran** [comment]
@pyskell @j-chimienti can you test it now? This should work after the latest CEW patch (3.11.3).

**Comment by j-chimienti** [comment]
Tested, working w/ trezor w/ PR #121

https://gastracker.io/tx/0xbd5ca32fe5d085af8cb2987d59e97e81fb1c8e0fb4044a7bb8b1df9d70208989
