### ISSUE TITLE
Difficult to manually edit gasLimit

### ISSUE THREAD

**Issue by pyskell** [EthereumCommonwealth/etherwallet#87]
This is a bit of a UI regression related to the gasLimit safety checks that were recently added.

My current work around is to highlight and start typing, without deleting the amount.

When trying to delete the 21, if the box ends up empty it resets it and gives this error message:

![image](https://user-images.githubusercontent.com/9665963/37781558-4e109dca-2dc7-11e8-91aa-92177a36bd90.png)

**Comment by Dexaran** [comment]
@j-chimienti It is necessary to change the `gasLimit` mechanic as follows:

- remove input checks when the user is typing the amount.

- check the amount of `Gas Price input box` once the textbox loses focus. IF the amount is correct then apply new gasPrice. Otherwise throw an error.
