### ISSUE TITLE
Make background node variable. (ETC node that processes DexNS/MessageSystem and other interchain calls)

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/etherwallet#89]
### Description

Currently there is the only node selection option: node that processes transactions.

![node2](https://user-images.githubusercontent.com/26142412/37788724-1857af88-2dfa-11e8-9276-edfa615964e8.png)

However, it turns out to be necessary to have the second node selection option for background node that will process interchain contract invocation calls (i.e. DexNS/ECNS and MessageSystem calls).

- background RPC node is ETC node that handles interchain invocations.
- one node can be a primary node (transactions) and a background node simultaneously.

**Comment by Dexaran** [comment]
@j-chimienti Epool node is hardcoded for MessageSystem as well. It should be replaced with `background node` variable as soon as it will be implemented: https://github.com/EthereumCommonwealth/etherwallet/blob/mercury/app/scripts/controllers/messagesCtrl.js#L94

**Comment by j-chimienti** [comment]
kk, I'll add background node in in DexNS/ECNS and MessageSystem controllers, watch for node change, and  switch background node  if necessary
